name: Build Steam Docker Image and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Containers
      run: make all

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Push docker images to DockerHub
      run: |
        docker push thetestgame/steam:stable
        docker push thetestgame/steam:latest
        docker push thetestgame/steam:winehq
        docker push thetestgame/steam:experimental
